"""M9.1a add users table

Revision ID: 27e00bcff992
Revises: 4aff9e134f16
Create Date: 2026-09-11 11:49:45.849800

Hand-authored, not autogenerated (M9.1a design doc §10.4): the ORM/schema
already has two known, deliberately unresolved drifts against the migration
chain (F-2: patients.nomor_rm UNIQUE; F-3: the four M8.4 indexes exist in the
chain but in no ORM model). ``alembic revision --autogenerate`` at this head
would therefore propose adding the unapproved F-2 constraint and dropping all
four M8.4 indexes alongside the intended ``users`` table. This migration adds
`` users`` alone and touches nothing else — F-2 and F-3 remain separate,
unresolved remediations, exactly as they were before this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e00bcff992'
down_revision: Union[str, None] = '4aff9e134f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the `users` table only (M9.1a Security Foundation).

    `role` is stored as VARCHAR with no CHECK constraint, matching the
    schema's existing convention (delivery_status / connection_status are the
    same "app-level enum" pattern) — see design doc §8.2.
    """
    op.create_table(
        "users",
        sa.Column("id_user", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("nama_lengkap", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("last_login_at", sa.TIMESTAMP(), nullable=True),
        sa.UniqueConstraint("username", name="users_username_key"),
    )


def downgrade() -> None:
    """Drop `users`. Exercised — see tests/test_migration_chain.py."""
    op.drop_table("users")
