"""M9.1b add audit_events table

Revision ID: 28aa370f5dbe
Revises: 27e00bcff992
Create Date: 2026-09-14 14:41:11.844166

Hand-authored, not autogenerated (M9.1b design doc §13 item 1; same rule that
governed 27e00bcff992). The ORM still carries two known, deliberately
unresolved drifts against the migration chain — F-2 (`patients.nomor_rm` not
yet UNIQUE) and F-3 (the four M8.4 indexes exist in the chain but in no ORM
model). `alembic revision --autogenerate` at this head would still propose
adding the unapproved F-2 constraint and dropping all four M8.4 indexes
alongside the intended `audit_events` table. This migration adds
`audit_events` alone and touches nothing else — F-2, F-3 and F-4 remain
untouched, exactly as before this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28aa370f5dbe'
down_revision: Union[str, None] = '27e00bcff992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the `audit_events` table only (M9.1b Audit Attribution).

    Append-only by application discipline (OD-B4) — no CHECK constraint on
    `action` / `entity_type` / `outcome`, matching the schema's existing
    convention for app-level string enums (`role`, `delivery_status`,
    `connection_status`). `entity_id` is intentionally not a foreign key —
    see `app/models/audit_event.py` for why. `id_user` is a real foreign key
    to `users.id_user` with ON DELETE RESTRICT.
    """
    op.create_table(
        "audit_events",
        sa.Column("id_audit", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("actor_username", sa.String(length=50), nullable=False),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("state_before", sa.String(length=30), nullable=True),
        sa.Column("state_after", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id_user"],
            name="fk_audit_events_id_user_users",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "idx_audit_events_entity",
        "audit_events",
        ["entity_type", "entity_id", "occurred_at"],
    )
    op.create_index(
        "idx_audit_events_actor",
        "audit_events",
        ["id_user", "occurred_at"],
    )


def downgrade() -> None:
    """Drop `audit_events` (and its indexes, implicitly, with the table).

    Exercised — see tests/test_migration_chain.py.
    """
    op.drop_index("idx_audit_events_actor", table_name="audit_events")
    op.drop_index("idx_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
