"""XN-550 Phase 1 raw capture: instrument_sessions + instrument_messages provenance

Revision ID: 5d2e8b7c41a9
Revises: 28aa370f5dbe
Create Date: 2026-09-17 18:00:00.000000

Hand-authored, not autogenerated (same rule as 27e00bcff992 / 28aa370f5dbe:
autogenerate would also propose the unapproved F-2 constraint and dropping the
F-3 M8.4 indexes). Implements
docs/instruments/sysmex_xn550/M9.2_IMPLEMENTATION_CONTRACT.md §9.1 and §9.2 for
G1 raw capture only:

* new table ``instrument_sessions`` (transport provenance, no PHI);
* additive, **nullable** provenance columns on ``instrument_messages`` — no
  backfill, existing (MLLP/BC-5150) rows keep NULL;
* technical constraints only: UNIQUE (id_session, stream_offset_start) and two
  integrity CHECKs. There is deliberately NO uniqueness on raw_sha256.

No observation (G2) tables, no clinical table changes, no data migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e8b7c41a9'
down_revision: Union[str, None] = '28aa370f5dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "instrument_sessions",
        sa.Column("id_session", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("id_instrument", sa.Integer(), nullable=False),
        sa.Column("transport_mode", sa.String(length=20), nullable=False),
        sa.Column("local_address", sa.String(length=45), nullable=False),
        sa.Column("local_port", sa.Integer(), nullable=False),
        sa.Column("peer_address", sa.String(length=45), nullable=False),
        sa.Column("peer_port", sa.Integer(), nullable=False),
        sa.Column("ack_policy", sa.String(length=50), nullable=False),
        sa.Column("opened_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("closed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("close_reason", sa.String(length=30), nullable=True),
        sa.Column("bytes_received", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("reads_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("acks_sent", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("messages_completed", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("fragments_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.ForeignKeyConstraint(
            ["id_instrument"],
            ["instruments.id_instrument"],
            name="fk_instrument_sessions_id_instrument_instruments",
        ),
    )
    op.create_index(
        "idx_instrument_sessions_instrument_opened",
        "instrument_sessions",
        ["id_instrument", sa.text("opened_at DESC")],
    )

    op.add_column("instrument_messages", sa.Column("id_session", sa.Integer(), nullable=True))
    op.add_column("instrument_messages", sa.Column("session_message_index", sa.Integer(), nullable=True))
    op.add_column("instrument_messages", sa.Column("stream_offset_start", sa.BigInteger(), nullable=True))
    op.add_column("instrument_messages", sa.Column("stream_offset_end", sa.BigInteger(), nullable=True))
    op.add_column("instrument_messages", sa.Column("raw_bytes", sa.LargeBinary(), nullable=True))
    op.add_column("instrument_messages", sa.Column("raw_sha256", sa.CHAR(length=64), nullable=True))
    op.add_column("instrument_messages", sa.Column("raw_length", sa.Integer(), nullable=True))
    op.add_column("instrument_messages", sa.Column("first_byte_at", sa.TIMESTAMP(), nullable=True))
    op.add_column("instrument_messages", sa.Column("read_count", sa.Integer(), nullable=True))
    op.add_column("instrument_messages", sa.Column("framing", sa.String(length=30), nullable=True))
    op.add_column("instrument_messages", sa.Column("parser_key", sa.String(length=50), nullable=True))
    op.add_column("instrument_messages", sa.Column("parser_version", sa.String(length=30), nullable=True))
    op.add_column("instrument_messages", sa.Column("duplicate_of_message_id", sa.Integer(), nullable=True))

    op.create_foreign_key(
        "fk_instrument_messages_id_session_instrument_sessions",
        "instrument_messages",
        "instrument_sessions",
        ["id_session"],
        ["id_session"],
    )
    op.create_foreign_key(
        "fk_instrument_messages_duplicate_of_instrument_messages",
        "instrument_messages",
        "instrument_messages",
        ["duplicate_of_message_id"],
        ["id_message"],
    )
    op.create_unique_constraint(
        "uk_instrument_messages_session_offset",
        "instrument_messages",
        ["id_session", "stream_offset_start"],
    )
    op.create_check_constraint(
        "ck_instrument_messages_raw_length",
        "instrument_messages",
        "raw_bytes IS NULL OR raw_length = octet_length(raw_bytes)",
    )
    op.create_check_constraint(
        "ck_instrument_messages_raw_sha256",
        "instrument_messages",
        "raw_bytes IS NULL OR raw_sha256 IS NOT NULL",
    )
    op.create_index(
        "idx_instrument_messages_instrument_sha256",
        "instrument_messages",
        ["id_instrument", "raw_sha256"],
    )
    op.create_index(
        "idx_instrument_messages_instrument_received",
        "instrument_messages",
        ["id_instrument", sa.text("received_at DESC")],
    )
    op.create_index(
        "idx_instrument_messages_duplicate_of",
        "instrument_messages",
        ["duplicate_of_message_id"],
    )


def downgrade() -> None:
    """Remove exactly what upgrade() added. Exercised in tests/test_migration_chain.py."""
    op.drop_index("idx_instrument_messages_duplicate_of", table_name="instrument_messages")
    op.drop_index("idx_instrument_messages_instrument_received", table_name="instrument_messages")
    op.drop_index("idx_instrument_messages_instrument_sha256", table_name="instrument_messages")
    op.drop_constraint("ck_instrument_messages_raw_sha256", "instrument_messages", type_="check")
    op.drop_constraint("ck_instrument_messages_raw_length", "instrument_messages", type_="check")
    op.drop_constraint("uk_instrument_messages_session_offset", "instrument_messages", type_="unique")
    op.drop_constraint(
        "fk_instrument_messages_duplicate_of_instrument_messages", "instrument_messages", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_instrument_messages_id_session_instrument_sessions", "instrument_messages", type_="foreignkey"
    )
    for column in (
        "duplicate_of_message_id",
        "parser_version",
        "parser_key",
        "framing",
        "read_count",
        "first_byte_at",
        "raw_length",
        "raw_sha256",
        "raw_bytes",
        "stream_offset_end",
        "stream_offset_start",
        "session_message_index",
        "id_session",
    ):
        op.drop_column("instrument_messages", column)
    op.drop_index("idx_instrument_sessions_instrument_opened", table_name="instrument_sessions")
    op.drop_table("instrument_sessions")
