"""add_instrument_runtime_status

Revision ID: 621889e316b5
Revises: 4a24240f8c32
Create Date: 2026-09-07 08:15:33.079794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621889e316b5'
down_revision: Union[str, None] = '4a24240f8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('connection_status', sa.String(length=50), nullable=True))
    op.add_column('instruments', sa.Column('last_status_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'last_status_at')
    op.drop_column('instruments', 'connection_status')
    # ### end Alembic commands ###
