"""XN-550 G2 unlinked observations: instrument_result_sets + instrument_result_items

Revision ID: 8a3023944bd1
Revises: 5d2e8b7c41a9
Create Date: 2026-09-18 12:00:00.000000

Hand-authored, not autogenerated (same rule as 27e00bcff992 / 28aa370f5dbe /
5d2e8b7c41a9: autogenerate would also propose the unapproved F-2 constraint and
dropping the F-3 M8.4 indexes). Implements
docs/instruments/sysmex_xn550/M9.2_IMPLEMENTATION_CONTRACT.md §10.2, §10.3 and
§10.6 exactly as closed in revision 6, after OD-XN-3 was approved (revision 7):

* two new tables only; no existing table is changed and no data is migrated;
* every foreign key is ON DELETE RESTRICT (observation rows are append-only
  provenance; no cascade);
* safety CHECKs only: identity status UNRESOLVED, duplicate status/pointer
  consistency (pointer always to a lower id), item kind, and "image references
  carry no value";
* indexes exactly as §10.2 / §10.3: none on sample_label, no redundant
  (id_result_set) item index, and no unique constraint on any content column.

There is deliberately no foreign key to patients / visits / orders / test_runs /
results: observations are never associated with a patient or specimen.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3023944bd1'
down_revision: Union[str, None] = '5d2e8b7c41a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "instrument_result_sets",
        sa.Column("id_result_set", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("id_message", sa.Integer(), nullable=False),
        sa.Column("id_instrument", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("analysis_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("sample_label", sa.String(length=100), nullable=False),
        sa.Column("association_status", sa.String(length=20), nullable=False),
        sa.Column("analysis_fingerprint", sa.CHAR(length=64), nullable=False),
        sa.Column("fingerprint_version", sa.Integer(), nullable=False),
        sa.Column("duplicate_status", sa.String(length=20), nullable=False),
        sa.Column("possible_duplicate_of", sa.Integer(), nullable=True),
        sa.Column("p5_populated", sa.Boolean(), nullable=False),
        sa.Column("p8_populated", sa.Boolean(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("non_n_flag_item_count", sa.Integer(), nullable=False),
        sa.Column("image_reference_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.UniqueConstraint("id_message", name="uk_instrument_result_sets_id_message"),
        sa.ForeignKeyConstraint(
            ["id_message"],
            ["instrument_messages.id_message"],
            name="fk_instrument_result_sets_id_message_instrument_messages",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_instrument"],
            ["instruments.id_instrument"],
            name="fk_instrument_result_sets_id_instrument_instruments",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["possible_duplicate_of"],
            ["instrument_result_sets.id_result_set"],
            name="fk_instrument_result_sets_possible_duplicate_of",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "association_status = 'UNRESOLVED'",
            name="ck_instrument_result_sets_association_status",
        ),
        sa.CheckConstraint(
            "(duplicate_status = 'NONE' AND possible_duplicate_of IS NULL) OR "
            "(duplicate_status = 'POSSIBLE_DUPLICATE' AND possible_duplicate_of IS NOT NULL "
            "AND possible_duplicate_of < id_result_set)",
            name="ck_instrument_result_sets_duplicate_state",
        ),
    )
    op.create_index(
        "idx_instrument_result_sets_fingerprint",
        "instrument_result_sets",
        ["id_instrument", "fingerprint_version", "analysis_fingerprint", "id_result_set"],
    )
    op.create_index(
        "idx_instrument_result_sets_received",
        "instrument_result_sets",
        [sa.text("received_at DESC"), sa.text("id_result_set DESC")],
    )
    op.create_index(
        "idx_instrument_result_sets_instrument_received",
        "instrument_result_sets",
        ["id_instrument", sa.text("received_at DESC"), sa.text("id_result_set DESC")],
    )

    op.create_table(
        "instrument_result_items",
        sa.Column("id_item", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("id_result_set", sa.Integer(), nullable=False),
        sa.Column("source_record_index", sa.Integer(), nullable=False),
        sa.Column("source_offset_start", sa.Integer(), nullable=False),
        sa.Column("source_offset_end", sa.Integer(), nullable=False),
        sa.Column("source_r_sequence", sa.Integer(), nullable=False),
        sa.Column("item_kind", sa.String(length=20), nullable=False),
        sa.Column("test_code", sa.String(length=50), nullable=False),
        sa.Column("test_code_qualifier", sa.String(length=10), nullable=True),
        sa.Column("value_raw", sa.String(length=50), nullable=True),
        sa.Column("units_raw", sa.String(length=20), nullable=True),
        sa.Column("reference_range_raw", sa.String(length=100), nullable=True),
        sa.Column("abnormal_flag_raw", sa.String(length=10), nullable=True),
        sa.Column("result_status_raw", sa.String(length=5), nullable=False),
        sa.UniqueConstraint(
            "id_result_set", "source_record_index", name="uk_instrument_result_items_set_record"
        ),
        sa.UniqueConstraint(
            "id_result_set", "test_code", name="uk_instrument_result_items_set_test_code"
        ),
        sa.ForeignKeyConstraint(
            ["id_result_set"],
            ["instrument_result_sets.id_result_set"],
            name="fk_instrument_result_items_id_result_set",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "item_kind IN ('MEASURED', 'INTERPRETIVE', 'FLAG_ONLY', 'IMAGE_REFERENCE')",
            name="ck_instrument_result_items_item_kind",
        ),
        sa.CheckConstraint(
            "(item_kind IN ('MEASURED', 'INTERPRETIVE') AND value_raw IS NOT NULL) OR "
            "(item_kind IN ('FLAG_ONLY', 'IMAGE_REFERENCE') AND value_raw IS NULL)",
            name="ck_instrument_result_items_value_by_kind",
        ),
    )


def downgrade() -> None:
    """Remove exactly what upgrade() added. Exercised in tests/test_migration_chain.py."""
    op.drop_table("instrument_result_items")
    op.drop_index("idx_instrument_result_sets_instrument_received", table_name="instrument_result_sets")
    op.drop_index("idx_instrument_result_sets_received", table_name="instrument_result_sets")
    op.drop_index("idx_instrument_result_sets_fingerprint", table_name="instrument_result_sets")
    op.drop_table("instrument_result_sets")
