"""M1_initial_schema

Revision ID: b1f9dbe772fa
Revises: 
Create Date: 2026-08-31 15:32:19.043508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1f9dbe772fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id_visit', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pasien', sa.Integer(), nullable=False),
    sa.Column('no_registrasi', sa.String(length=50), nullable=False),
    sa.Column('waktu_kunjungan', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_pasien'], ['patients.id_pasien'], ),
    sa.PrimaryKeyConstraint('id_visit'),
    sa.UniqueConstraint('no_registrasi')
    )
    op.create_table('test_runs',
    sa.Column('id_run', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_instrument', sa.Integer(), nullable=False),
    sa.Column('id_message', sa.Integer(), nullable=True),
    sa.Column('run_sequence', sa.Integer(), nullable=False),
    sa.Column('waktu_run', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delivery_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('delivered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_instrument'], ['instruments.id_instrument'], ),
    sa.ForeignKeyConstraint(['id_message'], ['instrument_messages.id_message'], ),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.PrimaryKeyConstraint('id_run'),
    sa.UniqueConstraint('id_order', 'run_sequence', name='uk_order_run_sequence')
    )
    op.create_index('idx_unique_final_run_per_order', 'test_runs', ['id_order'], unique=True, postgresql_where=sa.text('is_final = TRUE'))
    op.add_column('instrument_messages', sa.Column('error_detail', sa.Text(), nullable=True))
    op.alter_column('instrument_messages', 'id_instrument',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instrument_messages', 'parse_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Success'::character varying"))
    op.alter_column('instrument_messages', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('orders', sa.Column('id_visit', sa.Integer(), nullable=False))
    op.alter_column('orders', 'waktu_order',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'status_order',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Diproses'::character varying"))
    op.drop_constraint('orders_no_registrasi_key', 'orders', type_='unique')
    op.drop_constraint('orders_id_pasien_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'visits', ['id_visit'], ['id_visit'])
    op.drop_column('orders', 'no_registrasi')
    op.drop_column('orders', 'id_pasien')
    op.add_column('results', sa.Column('id_run', sa.Integer(), nullable=False))
    op.alter_column('results', 'waktu_hasil',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('unique_order_test', 'results', type_='unique')
    op.create_unique_constraint('uk_run_parameter', 'results', ['id_run', 'parameter_tes'])
    op.drop_constraint('results_id_message_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_id_instrument_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_id_order_fkey', 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'test_runs', ['id_run'], ['id_run'])
    op.drop_column('results', 'waktu_validasi')
    op.drop_column('results', 'id_message')
    op.drop_column('results', 'status_hasil')
    op.drop_column('results', 'id_instrument')
    op.drop_column('results', 'id_order')
    op.drop_column('results', 'divalidasi_oleh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('divalidasi_oleh', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('id_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('id_instrument', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('status_hasil', sa.VARCHAR(length=20), server_default=sa.text("'Menunggu Validasi'::character varying"), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('id_message', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('waktu_validasi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key('results_id_order_fkey', 'results', 'orders', ['id_order'], ['id_order'])
    op.create_foreign_key('results_id_instrument_fkey', 'results', 'instruments', ['id_instrument'], ['id_instrument'])
    op.create_foreign_key('results_id_message_fkey', 'results', 'instrument_messages', ['id_message'], ['id_message'])
    op.drop_constraint('uk_run_parameter', 'results', type_='unique')
    op.create_unique_constraint('unique_order_test', 'results', ['id_order', 'parameter_tes'], postgresql_nulls_not_distinct=False)
    op.alter_column('results', 'waktu_hasil',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('results', 'id_run')
    op.add_column('orders', sa.Column('id_pasien', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('no_registrasi', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_id_pasien_fkey', 'orders', 'patients', ['id_pasien'], ['id_pasien'])
    op.create_unique_constraint('orders_no_registrasi_key', 'orders', ['no_registrasi'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'status_order',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Diproses'::character varying"))
    op.alter_column('orders', 'waktu_order',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('orders', 'id_visit')
    op.alter_column('instrument_messages', 'received_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('instrument_messages', 'parse_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Success'::character varying"))
    op.alter_column('instrument_messages', 'id_instrument',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('instrument_messages', 'error_detail')
    op.drop_index('idx_unique_final_run_per_order', table_name='test_runs', postgresql_where=sa.text('is_final = TRUE'))
    op.drop_table('test_runs')
    op.drop_table('visits')
    # ### end Alembic commands ###
